### ISSUE TITLE
Update for Visual Studio 2015 RC?

### ISSUE THREAD

**Issue by jwood803** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#1]
Tried to follow the steps in VS 2015 RC and it seems to be missing some steps with there. Can this be updated for the RC?

**Comment by dstrockis** [comment]
Yes, the sample has only been tested against CTP6.  I will try to update for RC by end of the week.  Thanks @jwood803

**Comment by jwood803** [comment]
Thanks @dstrockis! To help here are a couple of things I noticed, though keep in mind they may be me being dumb. :p
- I used the ASP.NET 5 Preview Web Site template and I noticed that, while it created all the necessary files, it didn't seem to add everything to the project. I had to add everything I needed manually.
- I had to add the `Microsoft.Owin.Security.Cookies` NuGet package to resolve `CookieAuthenticationDefaults.AuthenticationType` error.

Let me know if there's anything I can do to help out.

**Comment by dstrockis** [comment]
Cool. Will do, thanks!

**Comment by jwood803** [comment]
Not sure why I didn't do this earlier, but if it helps I uploaded the solution I was using to a [repository](https://github.com/jwood803/AzureADTest).

**Comment by jwood803** [comment]
Just to keep everyone in the loop, I was able to get this to build by removing the `dnxcore50` section in the `project.json` file. It now looks like the below:

```
"frameworks": {
        "dnx451": { }
    },
```

Of course, now I get this run time error:

> Could not load file or assembly 'Microsoft.Framework.Logging.ILoggerFactory' or one of its dependencies. The system cannot find the file specified.

I wonder if this part actually needs the `dnxcore50` items.

EDIT: I also updated the [repository](https://github.com/jwood803/AzureADTest), if needed.

**Comment by levalencia** [comment]
please update it for RC, I also have the loggerfactory error and I am stuck :(

**Comment by jwood803** [comment]
I added `Microsoft.Framework.Logging` to the `project.json` file as well as remove any instances of `Microsoft.Framework.Logging` in the `project.lock.json` file and somehow still get the error message. I'm not quite sure what else to do.

EDIT: Thanks to some comments from this [StackOverflow question](http://stackoverflow.com/questions/30375231/could-not-load-file-or-assembly-microsoft-framework-logging-iloggerfactory-or) I updated one of the Authorization namespaces. It now "runs" but I just get a blank page. I've updated the [repo](https://github.com/jwood803/AzureADTest) with the latest.

**Comment by levalencia** [comment]
I also created my own REPO, thanks to Jon it now compiles, however I get this error 

An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to resolve service for type 'Microsoft.Framework.ConfigurationModel.IConfiguration' while attempting to activate 'WebApplication2.Controllers.HomeController'.

Microsoft.Framework.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)

https://github.com/levalencia/AzureADTestASPNET5OpenID

**Comment by levalencia** [comment]
any luck, I tried some posts at asp.net but they were deleted by the moderator with the excuse that it has a link to an external party :-1:

**Comment by r2musings** [comment]
Any updates here?!?  I am using jwood803's version and can run now under RC, but still can't get anything other than blank page with a 401. Not finding any way around it. I downloaded the VS2013 version of OpenID sample and it works, so I know that I have my config settings correct.

**Comment by r2musings** [comment]
I got this working finally. Will update jwood803's repo as soon as I clean it up.

**Comment by r2musings** [comment]
This is working in VS2015RC in this fork:  https://github.com/r2musings/AzureADTest

**Comment by heavenwing** [comment]
I create a pull request (https://github.com/AzureADSamples/WebApp-OpenIdConnect-AspNet5/pull/5) to support VS 2015 RC and dnx beta5

**Comment by dstrockis** [comment]
@tushargupta51 can you take a look at this?

**Comment by NBelham** [comment]
Not good that the documentation page cites a GitHub repository that specifies the use of beta5 and beta6 NuGet packages considering that rc1-final packages are available.

I then read above... This is working in VS2015RC in this fork: https://github.com/r2musings/AzureADTest
