### ISSUE TITLE
The instructions in 'How To Run This Sample' offer no clear instruction on what to do.

### ISSUE THREAD

**Issue by brentschmaltz** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#10]
The two links under: 'Getting started is simple! To run this sample you will need:'
Don't offer clear instruction on what to do. 

The first link (.NET Core & .NET Core SDK RC2 releases) - the user has a multiple of choices.
The second link (ASP.NET Core RC2 release) - is simply informational an it is not clear what the purpose is.

**Comment by dstrockis** [comment]
Thanks Brent! Will fix.
