### ISSUE TITLE
GraphApi

### ISSUE THREAD

**Issue by wangkanai** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#12]
Could you update this sample with GraphApi please?
Also in the mean time, how do we get the assign roles of the user
Also how do we assign role to a user, neither by portal first and then by code.

Thank you very much in advance :-)

**Comment by jmprieur** [comment]
There are other samples illustrating the graph api (https://github.com/Azure-Samples?utf8=%E2%9C%93&q=graphapi&type=&language=)

To understand about roles, I suggest looking at [active-directory-Dotnet-webapp-roleclaims](https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims)
