### ISSUE TITLE
Poor article: Integrating Azure AD into an ASP.NET Core web app

### ISSUE THREAD

**Issue by cdiddy77** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#13]
https://azure.microsoft.com/en-us/documentation/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/

Why is it poor? Because it claims:
"This sample shows how to build a .Net MVC web application that uses OpenID Connect to sign-in users from a single Azure Active Directory tenant, using the ASP.Net Core OpenID Connect middleware."

What it actually does is guide you through how to fill out the forms on Azure to create a new AAD application, and then copy/paste a few pieces of data into the sample application.

What it should do instead, is explain all of the deltas between a plain ASP.NET Core web app, and the version modified to support AAD. Even if it doesn't explain why you copy/paste code into specific parts, at least it would help folks. Folks come to the article not because they want to develop the WebApp-OpenIdConnect-DotNet application, but because they want to take their existing app and modify it to use AAD. So give us the information we need to complete that task.

Please and thanks.

**Comment by dstrockis** [comment]
Thanks for the feedback! I totally agree.  We have a bunch of tutorials posted on aka.ms/aaddev that sort of do what your asking for.  We just haven't had the time to write one for this sample yet - there were lots of people out there that just wanted to see some working code so they could get started, so we published this code sans-tutorial.

Could you take a look at those articles and see if that format would be more to your liking?

**Comment by jmprieur** [comment]
Copied to the backlog (tutorials)
