### ISSUE TITLE
This site can’t be reached  localhost refused to connect.

### ISSUE THREAD

**Issue by samdevx1029** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#15]
Does not work after all the work that went into AAD. Compiled successfully, followed instructions successfully to enter AAD tenant and clientId in config json. When I run it from Visual Studio, following error comes up.

This site can’t be reached  
localhost refused to connect.

I don't know where to begin to troubleshoot this. Can you help? I really want this to work.

**Comment by jmprieur** [comment]
This must have been an issue with IISExpress. closing this issue for new
