### ISSUE TITLE
ChallengeAsync not working

### ISSUE THREAD

**Issue by AnnejanBarelds** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#16]
Hi,

I'm having trouble getting the OpenID Challenge to work when using this sample. In my scenario I'm already signed in, but I want to issue a new OpenID Connect challenge. This is needed for example in cases where the ADAL token cache is empty while the user presents a valid cookie from a previous session. In those cases, a challenge should redirect the user to the auth endpoint, resulting in a new auth token to be presented to the app.

However, I don't seem to get this working: I'm being redirected to the Access Denied URL as configured in the cookie middleware. What am I doing wrong?

Thanks in advance for any nudge in the right direction.

**Comment by jmprieur** [comment]
I believe that his now works with the recent versions of this sample
