### ISSUE TITLE
Add more detail to what config items we need

### ISSUE THREAD

**Issue by jwood803** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#2]
Is it possible to add a bit more detail and maybe some screenshots to make it clearer what items we need to include in our `config.json` file? For instance, I'm still a bit confused as to what the Tenant is and how to put that into the config.

**Comment by jmprieur** [comment]
The readme (How to run this sample) provides a link on how to get an Azure AD tenant.
