### ISSUE TITLE
How to you get Azure b2c edit profile to work?

### ISSUE THREAD

**Issue by Bigshooter** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#20]
How to you get Azure b2c edit profile to work?

I have tried the code below and it always redirects to forbidden.

```
var authenticationProperties = new AuthenticationProperties { RedirectUri = "/" };
                    await HttpContext.Authentication.ChallengeAsync(Startup.EditPolicyId.ToLower(), authenticationProperties);
```

**Comment by Bigshooter** [comment]
Is this the preferred method?

https://dzimchuk.net/azure-ad-b2c-user-profile-editing-issues-with-asp-net-core/

or 

https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c/issues/2

**Comment by dstrockis** [comment]
Addressed in https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c/issues/2
