### ISSUE TITLE
 The reply address 'https://localhost:44353/signin-oidc' does not match the reply addresses 

### ISSUE THREAD

**Issue by jrmcdona** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#22]
I have changed the reply address in the config.json ,  have also cleaned the solution and rebuilt.   But I cannot shake this error.

Additional technical information: 
Correlation ID: 465125a3-feb6-4ce2-9b2a-8313d16d5c03 
Timestamp: 2017-05-12 16:59:48Z 
AADSTS50011: The reply address 'https://localhost:44353/signin-oidc' does not match the reply addresses configured for the application: 'dc695b2d-b6d5-47f5-bdfa-eb7daf7a1cbd'. More details: not specified 

Any idea?

Thanks

**Comment by ccit-spence** [comment]
You need to update the reply address within Azure.

**Comment by somashekarg** [comment]
i am getting" Sorry we recieved a bad request error " after signing in to the app

please let me know why i am getting this error 

The reply address 'https://localhost:44353/signin-oidc' does not match the reply addresses configured for the application: '20348634-8864-49a7-b3b9-fbab9dbf0bb6'. More details: not specified
