### ISSUE TITLE
Update the README.md file in the aspnet_core_2_0 branch

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#26]
use the aspnet_core_2_0 branch
Look at the readme

Expected:
It explains the ASP.NET Core 2.0 code

Actual
It's still about ASP.NET Core 1.x

**Comment by Programm3r** [comment]
Agreed - documentation about how to do it in Core 2.0 is non existent - everything is marked as obsolete
