### ISSUE TITLE
OpenIdConnectOptions creating is BUG!

### ISSUE THREAD

**Issue by marioinz** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#27]
https://stackoverflow.com/questions/45742034/asp-net-core-2-0-argumentexception-options-clientid-must-be-provided
proper action is to change properties of input instead returning new object

**Comment by jmprieur** [comment]
Thanks for the feedback. This is fixed in the ASP.NET 2.0 version.

**Comment by marioinz** [comment]
it is not ;]

**Comment by jmprieur** [comment]
I'm confused, @marioinz . I don't create any objects anymore: 
- https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/blob/master/WebApp-OpenIDConnect-DotNet/Startup.cs#L36
- https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/blob/master/WebApp-OpenIDConnect-DotNet/Startup.cs#L44 

What do you expect?

**Comment by jmprieur** [comment]
Also which symptom do you see? (the sample works for me?)

**Comment by marioinz** [comment]
now code of sample is corrected.
but your replay from last hour suggest that issue was resolved with new framework - which is not true :) no offence :)

**Comment by jmprieur** [comment]
oh, sorry. I was not clear. I mean the latest version of the sample.
Thanks for confirming @marioinz
