### ISSUE TITLE
How to authenticate in SPA on different domain than ASP.NET Core Backend with CORS enabled

### ISSUE THREAD

**Issue by Liero** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#28]
How should I modify your ASP.NET Core 2 sample in order to enable CORS scenario?

Currently, the sample redirects to backend's domain root. 
_E.g. I redirect from localhost/index.html to www.myapp.net/account/login -> redirects to Identity Provider's login -> redirects to www.myapp.net_

When I modify the sample with return url, the frontend running on different domain is not authenticated:

```
[HttpGet("login")]
public async Task Login(string returnUrl = null)
{
    await HttpContext.ChallengeAsync(
        OpenIdConnectDefaults.AuthenticationScheme,
        new AuthenticationProperties { RedirectUri = returnUrl });
}
```

_E.g. I redirect from localhost/index.html to www.myapp.net/account/login?returnUrl=http://localhost/index.html -> redirects to Identity Provider's login -> redirects back to localhost/index.html -> request made from localhost are still not authenticated_

**Comment by jmprieur** [comment]
Hi @Liero : did you have a look at https://docs.microsoft.com/en-us/aspnet/core/security/cors ?

**Comment by Liero** [comment]
Hi,

after reviewing the article once more I found out that I was missing [this part](https://docs.microsoft.com/en-us/aspnet/core/security/cors#credentials-in-cross-origin-requests) in my javascript code:

```javascript
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;
```
resp:

```javascript
$.ajax({
  type: 'get',
  url: 'http://www.example.com/home',
  xhrFields: {
    withCredentials: true
}
```

Thank you very much. Would you like to take credit on stackoverflow?

**Comment by Liero** [comment]
Hmm, this doesn't work in Chrome. It works in Edge, but not in Chrome.
I've setup CORS like this:

```
 var corsPolicy = new CorsPolicyBuilder(new CorsPolicy())
                .AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials()
                .Build();
```

for more info: https://stackoverflow.com/questions/46582731/xhr-withcredentials-true-does-not-work-in-chrome

**Comment by Liero** [comment]
After some investigation I found out, that Chrome refuses to send .AspNetCore.Cookie, because they have property **SameSite=lax**

I believe this is BUG and it it very simmilar to this: https://github.com/IdentityServer/IdentityServer4/issues/1370

Since this is quite critical for us, could you suggest some workaround?

**Comment by XenonLX** [comment]
Try using inside your backend service configuration section (Usually located somewhere in startup files)
`options.Cookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None;`
So it will look like this:
```
services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
	.AddCookie(options =>
	{
		options.Cookie.HttpOnly = true;
		options.Cookie.Name = "MyAppCookie";
		options.Cookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None;
	});
```

**Comment by jmprieur** [comment]
Closing as we are archiving this repo
