### ISSUE TITLE
Configure session timeout

### ISSUE THREAD

**Issue by sidharthancr** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#31]
Hi, I am using Azure ad with .net core 2.0. I want to session timeout after 1 hour. But its not working.
I used session with cookie. Please help me.

    ` services.AddDistributedMemoryCache();
              services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromMinutes(10);

            });
            services.AddMvc();
            // Add Authentication services.
            services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
                // Configure the OWIN pipeline to use cookie auth.
                // Configure the OWIN pipeline to use OpenID Connect auth.
                .AddOpenIdConnect(option =>
                {
                    option.UseTokenLifetime = true;
                    option.ClientId = Configuration["AzureAD:ClientId"];
                    option.Authority = String.Format(Configuration["AzureAd:AadInstance"], Configuration["AzureAd:Tenant"]);
                    option.SignedOutRedirectUri = Configuration["AzureAd:PostLogoutRedirectUri"];
                    option.Events = new OpenIdConnectEvents
                    {
                        OnRemoteFailure = OnAuthenticationFailed,
                       // OnTicketReceived = OnTicketReceived
                    };
                }).AddCookie(options =>
                {
                    options.ExpireTimeSpan = TimeSpan.FromSeconds(10);
                    options.LoginPath = "/Account/LogIn";
                    options.LogoutPath = "/Account/LogOff";
                    options.SlidingExpiration = false;
                    options.Cookie = new CookieBuilder
                    {
                        Name = "LeadsConnect",
                        Expiration = TimeSpan.FromSeconds(10),

                    };
                });`

**Comment by jmprieur** [comment]
Closing as we are archiving this repo
