### ISSUE TITLE
Instructions incomplete

### ISSUE THREAD

**Issue by RolandLeFranc** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#33]
I have followed the instructions in the README and hit the following error. It would be great if you could enhance them.
----
Sign in
Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply address 'http://localhost:55643/signin-oidc' does not match the reply addresses configured for the application: 'd8e54159-61d2-4956-adad-cd7160824bb4'. More details: not specified

**Comment by RolandLeFranc** [comment]
I had to add http://localhost:55643/signin-oidc to the list of Reply URLS in the Azure AAD settings.

**Comment by jmprieur** [comment]
I understand that IIS Express ran the sample from localhost:55643 and not localhost:5000 as explained in the Readme.md. See step 1.5.
Now why was the sample run from a different base URL? did you change it, @RolandLeFranc ?

**Comment by RolandLeFranc** [comment]
It's not about the port being different. The step is missing in the doc.

**Comment by jmprieur** [comment]
Do you want something else than step 1.5 ?

**Comment by taggie05** [comment]
We had the same issue we had to add localhost to the reply url. Why exactly is a localhost url needed in a reply url in Azure Registered App ? I want to understand why we need to input a localhost url and why the error: AADSTS50011 is occurring without it.

**Comment by jmprieur** [comment]
@taggie05 : what happens is that the authentication is **delegated** to Azure Active Directory, which let the user enter the credentials, do the multi-factor authentication (if needed) and other conditional access, requests consent from the user (if needed), and then calls back the application at the Reply URL with the access token (or, in this case, a code that can be redeemed to get an access token).
As long as you are running the Web app in a local browser, you need this Reply URL.
When you deploy it to Azure (for instance), you'll need to update the Reply URLs in the application registration.
