### ISSUE TITLE
Does not use the ClientSecret value

### ISSUE THREAD

**Issue by AjmalVh** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#34]
I can see, this sample does not uses the ClientSecret from AzureAdOptions. Few other samples, for example [this one](https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore), uses ClientSecert. What is the difference here?

**Comment by jmprieur** [comment]
@AjmalVh : this sample is a Web App which lets the user sign-in, but does not call any Web API.
The [dotnet-webapp-webapi-openidconnect-aspnetcore](https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore) sample is a Web App which let's the user sign-in and **then calls a Web API in the name of the user**, using ADAL.NET's [on behalf of flow](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Service-to-service-calls-on-behalf-of-the-user).
When Web Apps or Web APIs call another Web API, as they are [confidential clients applications](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-a-token-return-AuthenticationResult-and-possibly-UserInfo#confidential-client-applications), they need to provide an application secret which was previously share with Azure AD.

**Comment by AjmalVh** [comment]
Crystal clear :+1:  Thanks @jmprieur
