### ISSUE TITLE
Identity - not authenticated and claims are missing

### ISSUE THREAD

**Issue by DavidDury** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#35]
I followed your example and works fine the only difference is that the controller where I want to login with Azure AD instead of [Authorize] I added: [Authorize(AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme)]. But all works good. The scenario is: use Azure AD to login only for a specific section of the site and ASP.NET Core 2.0 Identity for the rest of the site.

When I go to my controller I am redirect to Azure AD log in and redirected back to the application. All good here, User.Identity.IsAuthenticated is true, claims are present, etc. Works fine. if then I am navigating to another controller that is not using any [Authorize] attribute then User.Identity.IsAuthenticated is false and no claims are present. So basically I am navigating to the controller after I login with AD so I assume the Identity should be there. Am I doing something wrong?

**Comment by jmprieur** [comment]
Closing as we are archiving this repo
