### ISSUE TITLE
After login browsers loops between azure ad and app, until fail with bad request

### ISSUE THREAD

**Issue by mmsommer** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#36]
I tried to implement this sample in .net core 2.1. At first it looks like it is working, it is redirecting me to the login page of azure AD of my company. But after loggin in I can see that the browser is looping from my application to azure ad and back, until after a while it just fails with a "bad request - headers too long".

Do you know of this issue and do you have any suggestions?

**Comment by dsyorkd** [comment]
I'm seeing this behavior in Safari, where as in Chrome everything seems to be working fine.

**Comment by da1rren** [comment]
Hey Guys,

We had this issue it seems to be because of a breaking change in chromium see for a fix:
https://community.auth0.com/t/authentication-broken-on-asp-net-core-and-safari-on-ios-12-mojave-take-2/19104/2

For the bug:
https://bugs.webkit.org/show_bug.cgi?id=188165

Hope that helps!
