### ISSUE TITLE
AddAzureAd method name change in .NET Core 2.1

### ISSUE THREAD

**Issue by zachesposito** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#37]
This isn't necessarily a problem but just wanted to point out that AzureADAuthenticationBuilderExtensions.AddAzureA**d** is now AzureADAuthenticationBuilderExtensions.AddAzureA**D** (uppercase) in [.NET Core 2.1](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.azureadauthenticationbuilderextensions.addazuread?view=aspnetcore-2.1). Took me a couple hours to figure out why .AddAzureAd wasn't recognized in my 2.1 project.

**Comment by jmprieur** [comment]
Thanks for reporting, @zachesposito 
We need to update fix the sample and fix it

cc:  @andretms FYI

**Comment by jmprieur** [comment]
This is solved in the new sample https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC
