### ISSUE TITLE
appsettings.json TenantId and ClientId

### ISSUE THREAD

**Issue by srifellc** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#39]
In the demo, the TenantId, and ClientId were automatically placed in the appsettings.json.  My question is;  do these two pieces of information need to be protected?  Is it ok for them to be in the appsettings.json, and then in source control?

Or should these value be saved in the Secrets Manager?

BTW, excellent demo.  I really like how with one line of code at the command line I was able to build a sample that worked on the first shot.

**Comment by jmprieur** [comment]
@srifellc : TenantId and ClientID are fine in the appsettins.json and source control. They can appear on the URLs, BTW.

Note however (not strictly related to this question), that for Web Apps which will then require calling an API, they would need to use confidential client application flows which would require a client secret (or certificate) This one would be fine in the appsetings.json (your web app is probably running on a server or in Azure), but probably not in source control

Proposing to close this question
