### ISSUE TITLE
Must enable options.AutomaticAuthentication for [Authorize] to work properly

### ISSUE THREAD

**Issue by jonfreeland** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#4]
To get `[Authorize]` to work properly, I had to enable `options.AutomaticAuthentication` in `app.UseOpenIdConnectAuthentication(options => { ... });`. Otherwise, I would just get an immediate empty 401 response. Is this correct approach? If so, can you update the sample to indicate this? If not, can you explain what the proper approach is?

Also, there is a [SO question](http://stackoverflow.com/questions/31321329/using-authorize-with-openidconnect-in-mvc-6-results-in-immediate-empty-401-res) referring to this.

Thanks!

**Comment by jmprieur** [comment]
This is no longer needed with the ASP.NET core 2.0 sample (https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/tree/aspnet_core_2_0)
