### ISSUE TITLE
How to make this work with Azure AD B2C?

### ISSUE THREAD

**Issue by dstrockis** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#7]

**Comment by dstrockis** [comment]
Opening this issue while an ASP Net 5 sample is not available for Azure AD B2C

**Comment by guardrex** [comment]
@dstrockis Thanks ... I'll keep it as quick as I can ... know ur crazy busy there.

`ChallengeRespnse` to hit up AAD B2C for signup, signin, signout, and profile edits probably can be made to work (I think) with the existing package `Microsoft.AspNet.Authentication.OpenIdConnect 1.0.0-beta7`, and I think I'm just not doing something correctly.

Note that this is for `dnxcore50`-only projects, so the Owin packages (`net45`-only) are no help to me (at least until they go `dnxcore50`, if they do).

The manual approach (`redirect_uri` below) works ... my clearly wrong `ChallengeResponse` isn't. I provide an example of the signin code below, but I get the same outcome for all three types of challenges.

After a manually-built Uri challenge for signin (or for signup, signout, or profile edit), tokens and claims are good. The links work fine.

`ChallengeResponse` is not populating the `RedirectUri` with anything, in spite of OpenIdConnect configuration provided in `Startup` and everything else basically working. Therefore, nothing happens returning a `ChallengeResponse` in a controller.

Is this a "Luke problem" or a "that package isn't ready for this yet problem?"

![capture1](https://cloud.githubusercontent.com/assets/1622880/10054916/3488d44a-61f9-11e5-9b4d-ec047641c779.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1622880/10054917/382c950a-61f9-11e5-9e52-4d28ff3e4576.PNG)

Side Note: One thing bothering me is that the authority in OpenIdConnect is ...

``` c#
options.Authority = 
    $"https://login.microsoftonline.com/{Tenant}/v2.0/.well-known/openid-configuration"; 
```

... but the STS endpoint for signin, signup, edit profile is ...

``` html
https://login.microsoftonline.com/XXXXXXXXXX.onmicrosoft.com/oauth2/v2.0/authorize
```

... for signout ...

``` c#
context.HttpContext.Response.Redirect(
    "https://login.microsoftonline.com/XXXXXXXXXX.onmicrosoft.com/oauth2/v2.0/logout" +
        "?p=B2C_1_SigninPolicy" + 
        Startup.RedirectUrl
);
```

... so I'm wondering if these different endpoints are are part of my problem (or just a problem generally).

btw-- An "acceptable answer" to me, too, is just "Chill!" ... I might be coming to this with these questions too early in the Preview. If I just need to wait a few weeks or months for package updates (e.g., the Owin packages get some `dnxcore50` goodness), then I'll just wait.

**Comment by dstrockis** [comment]
In your `ChallengeResult` you should be able to set the `AuthenticationProperties.RedirectUri` property to whatever redirect URI you want.  The theory being that each challenge you issue might want to return the user to a different page in your app.  See if that helps.

I think you already know this, but be aware that the dictionary you provide is just an arbitrary bag for information that you want to access elsewhere in the OWIN pipeline - like, in the RedirectToIdentityProvider notification where you can append the policy parameter to the outgoing `/authorize` request.

Re: side note.  That shouldn't be the value of the authority... That's the metadata endpoint.  I'd have to take a closer look to see where that's being set.  If you want to share your startup code I can look.

I appreciate the gung-ho attitude :) No need to chill... You should be able to get this to work with the existing packages.  I just hope you can understand that our ability to help you out with speedbumps along the way is somewhat limited.  A more efficient way for me to help you (& many others) out would be to spend time producing useful samples & docs.  We just haven't quite gotten there yet

**Comment by guardrex** [comment]
@dstrockis Thanks ... that did clear up two misunderstandings that I had.

Let's close ... there are too many problems (on my end) trying to get it working for `dnxcore50`, and it's a little early in the Preview to expect something for `dnxcore50` with so much of the Core CLR in flux. Even if you had something for beta7 now, it would probably break for beta8 ... and break again for RC.

I'll just keep an eye out for more docs and samples as they arrive. Thanks again for your help!

**Comment by nhwilly** [comment]
Thanks for the discussion guys.  I was going to try to spin up something on the latest ASP.NET, but it looks like it's too soon for me.  Then there's the little fact that I'd be lost for about a month trying to sort through it.

**Comment by guardrex** [comment]
@nhwilly It will (mostly) work if you create manual links as I did. You have to disable the nonce checking with

```
options.ProtocolValidator.RequireNonce = false;
```

It isn't so much that you can't generate a nonce to add to the manually-created challenge links (example of such a link for signon is below), as this looked promising at first:

```
string nonce = openIdConnectOptions.ProtocolValidator.GenerateNonce();
Context.User.AddIdentity(new ClaimsIdentity(new Claim[] { new Claim("nonce", nonce) }, OpenIdConnectAuthenticationDefaults.AuthenticationScheme));
string protectedNonce = openIdConnectOptions.StringDataFormat.Protect(nonce);
Response.Cookies.Append(".AspNet.OpenIdConnect.Nonce." + protectedNonce, "N", new CookieOptions { HttpOnly = true, Secure = Request.IsHttps });
Context.Response.Redirect(
    "https://login.microsoftonline.com/XXXXXX.onmicrosoft.com/oauth2/v2.0/authorize" +
    "?p=B2C_1_SigninPolicy" +
    "&client_id=xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx" +
    "&response_type=id_token" +
    "&scope=openid" +
    "&response_mode=form_post" +
    "&redirect_uri=" + Startup.RedirectUrl +
    "&nonce=" + nonce
);
```

where `openIdConnectOptions` is passed into the controller as `OpenIdConnectAuthenticationOptions` and the `RedirectUrl` is a Url-escaped FQN to where they should be sent back after B2C auth, but the `StringDataFormat.Protect(nonce)` broke for me. I just couldn't get a hold of the method to protect the nonce for that cookie ... probably something silly I'm not doing.

After the issue of having it running without nonce checking, you'll notice some bizarre behavior when you challenge the service for a user profile edit. The UI that loads in AAD B2C will act like it's working in more of a "sign-up" mode than than a "edit profile" mode **after** you have already created the account and have **already** used it to Sign-On (i.e., the text for a profile edit will say "Create your account by providing the following details" with a "Create" button; and after you click "Create," it will say to stand by while your account is being created. They're obviously going to fix that.

Other issues: User attributes don't allow spaces, so you'd be limited for two-word attributes of scrunching them together (e.g., shoe size would go in as "ShoeSize" (no space) and display in the AAD B2C UI as "ShoeSize" (no space), which doesn't look too good. Finally, you won't be able to get bearer tokens for Graph API or other API's that you might need to manually hit [e.g., Key Vault, b/c the Key Vault API isn't ready yet and you need to manually hit it with an `HttpClient` request (with a bearer token from AAD)]. Not having access to the Graph API particularly hurts, since I need to get a user's group memberships in order for the app to grant them access to various parts of the app.

Anyway, I'm sure this will all get sorted out soon enough. @dstrockis produces excellent samples, so I'm lick'in my chops to see his version of AAD B2C for Core CLR. In the meantime if you want to play with it and get stuck, you can hit me up, and I'll post code bits if you want to get at least as far as I got.

**Comment by nhwilly** [comment]
Wow. Super generous offer, but I'm probably boxing above my weight class.

I'll look at it, but I can't be sure I can get through it.

Thanks.  Offers like this remind me of the internet a long time ago.  Very cool.

Sent from my Windows Phone

**Comment by guardrex** [comment]
> I'm probably boxing above my weight class

Welcome to the club!

Here's a repo of my goofings-off with it ... https://github.com/GuardRex/AZUREB2C

If you follow the walk-through that they put up with this code, it should work. Check out https://azure.microsoft.com/en-us/documentation/articles/active-directory-b2c-devquickstarts-web-dotnet/. Their stuff uses the Owin packages, but those aren't `dnxcore50`-friendly, and I'm working in the Core CLR; therefore, you'll see some differences here and there between what they say to do and what I did.

**Comment by codeConcussion** [comment]
+1! Please update back here when you have a ASP.NET 5 example for B2C.

**Comment by ghost** [comment]
Is there any update on getting openidconnect in aspnet5 working with Azure B2C?

**Comment by flgarrid** [comment]
+1

Looking forward to a full demo of aspnet5 working with Azure B2C!

**Comment by CharlBest1** [comment]
I also can't wait! :smile:

**Comment by flgarrid** [comment]
Finally its working for me. You can check my implementation in https://github.com/qpler/smartgov (a project my team is developing). Make sure you take a close look at startup.cs and webcontroller.cs.

**Comment by ghost** [comment]
Sorry, I am seeing lots of html and xml files, but nothing that resembles an asp.net app.

Is this the correct link?

Philip

**Comment by flgarrid** [comment]
Had to move everything to a private repo, so I'll leave the code here:

Startup.cs

```
     public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
      {

        .....................

        Tenant = "xxxxxxxxx.onmicrosoft.com";
        ClientId = "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx";

        SignUpPolicyId = "xxxxxxxxxxxxxx";
        SignInPolicyId = "xxxxxxxxxxxxxx";
        ProfilePolicyId = "xxxxxxxxxxxxxx";
        PolicyKey = "b2cpolicy";
        AcrClaimType = "http://schemas.microsoft.com/claims/authnclassreference";

        AadInstance = "https://login.microsoftonline.com/{0}{1}{2}";

        app.UseCookieAuthentication(options =>
        { 
            options.AutomaticAuthenticate = true;
        });

        app.UseOpenIdConnectAuthentication(options => 
            {
                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.ClientId = ClientId;
                options.Authority = string.Format(CultureInfo.InvariantCulture, AadInstance, Tenant,string.Empty,string.Empty);
                options.ResponseType = OpenIdConnectResponseTypes.IdToken;
                options.ConfigurationManager = new PolicyConfigurationManager(
                String.Format(CultureInfo.InvariantCulture, AadInstance, Tenant, "/v2.0","/" + OpenIdProviderMetadataNames.Discovery),
                new string[] { SignUpPolicyId, SignInPolicyId, ProfilePolicyId});
                options.Events = new OpenIdConnectEvents {
                    OnMessageReceived = OnMessageReceived,
                    OnAuthenticationFailed =   OnAuthenticationFailed,
                    OnRedirectToAuthenticationEndpoint = OnRedirectToAuthenticationEndpoint
                };
            }
        );   
    }
    private Task OnAuthenticationFailed(AuthenticationFailedContext context)
    {
        context.Response.Redirect("xxxxxxxxxxx?message=" + context.Exception.Message);
        context.HandleResponse();
        return Task.FromResult(0);
    }
    private async Task OnRedirectToAuthenticationEndpoint(RedirectContext context)
    {
        PolicyConfigurationManager mgr = context.Options.ConfigurationManager as PolicyConfigurationManager;
        if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
        {
            if (context.Request.Path.Value.ToLower().Contains("signup"))
            {
                OpenIdConnectConfiguration config = await mgr.GetConfigurationByPolicyAsync(CancellationToken.None, SignUpPolicyId);
                context.ProtocolMessage.IssuerAddress = config.EndSessionEndpoint;
            }
            else if (context.Request.Path.Value.ToLower().Contains("signin"))
            {
                OpenIdConnectConfiguration config = await mgr.GetConfigurationByPolicyAsync(CancellationToken.None, SignInPolicyId);
                context.ProtocolMessage.IssuerAddress = config.EndSessionEndpoint;
            }
            else if (context.Request.Path.Value.ToLower().Contains("profile"))
            {
                OpenIdConnectConfiguration config = await mgr.GetConfigurationByPolicyAsync(CancellationToken.None, ProfilePolicyId);
                context.ProtocolMessage.IssuerAddress = config.EndSessionEndpoint;
            }
        }
        else
        {
            if (context.Request.Path.Value.ToLower().Contains("signup"))
            {
                OpenIdConnectConfiguration config = await mgr.GetConfigurationByPolicyAsync(CancellationToken.None, SignUpPolicyId);
                context.ProtocolMessage.IssuerAddress = config.AuthorizationEndpoint;
            }
            else if (context.Request.Path.Value.ToLower().Contains("signin"))
            {
                OpenIdConnectConfiguration config = await mgr.GetConfigurationByPolicyAsync(CancellationToken.None, SignInPolicyId);
                context.ProtocolMessage.IssuerAddress = config.AuthorizationEndpoint;
            }
            else if (context.Request.Path.Value.ToLower().Contains("profile"))
            {
                OpenIdConnectConfiguration config = await mgr.GetConfigurationByPolicyAsync(CancellationToken.None, ProfilePolicyId);
                context.ProtocolMessage.IssuerAddress = config.AuthorizationEndpoint;
            }
        }
    }
```

AccountController.cs:

```
        [HttpGet("login")]    
       public object LogIn()
        {
            if (HttpContext.User == null || !HttpContext.User.Identity.IsAuthenticated)
                return new ChallengeResult(OpenIdConnectDefaults.AuthenticationScheme,
                    new AuthenticationProperties(new Dictionary<string, string> {
                             {Startup.PolicyKey, Startup.SignInPolicyId}
                         }));
            Response.Redirect("http://xxxxxxxxxxxxxxxx");
            return true;
        }
```

```
    [HttpGet("userinfo")]
    public object userinfo()
    {

        if (HttpContext.User.Identity.IsAuthenticated)
        return new {Name = HttpContext.User.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname").Value, Surname=HttpContext.User.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname").Value, Email=HttpContext.User.FindFirst("emails").Value, ID=HttpContext.User.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value};
        return String.Empty;
    }
    [HttpGet("profile")]
    public object profile()
    {
        if (HttpContext.User.Identity.IsAuthenticated)
            return new ChallengeResult(OpenIdConnectDefaults.AuthenticationScheme,
                new AuthenticationProperties(new Dictionary<string, string> {
                         {Startup.PolicyKey, Startup.ProfilePolicyId}
                     }));
        Response.Redirect("http://xxxxxxxxxxxxxxxxxxx");
        return true;
    }
    [HttpGet("signup")]
    public object signup()
    {
        if (HttpContext.User == null || !HttpContext.User.Identity.IsAuthenticated)
            return new ChallengeResult(OpenIdConnectDefaults.AuthenticationScheme,
                new AuthenticationProperties(new Dictionary<string, string> {
                         {Startup.PolicyKey, Startup.SignUpPolicyId}
                     }));
        Response.Redirect("http://xxxxxxxxxxxxxxxx");
        return true;
    }
    [HttpGet("signout")]
    public object SignOut()
    {
        if (HttpContext.User.Identity.IsAuthenticated)
        {
            HttpContext.Authentication.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme,
                new AuthenticationProperties(new Dictionary<string, string> {
                     {Startup.PolicyKey, HttpContext.User.FindFirst(Startup.AcrClaimType).Value}
                 }));
            HttpContext.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new AuthenticationProperties(new Dictionary<string, string> {
                     {Startup.PolicyKey, HttpContext.User.FindFirst(Startup.AcrClaimType).Value}
                 }));
            Response.Redirect("https://login.microsoftonline.com/" + Startup.Tenant + "/oauth2/v2.0/logout?p=" + Startup.SignInPolicyId + "&redirect_uri=http%3A%2F%2Fxxxxxxxxxxxxx");
        }
        return true;
    }
```

**Comment by Bigshooter** [comment]
Is this example the best way to do this now?

**Comment by gsacavdm** [comment]
@Bigshooter, we now have an official dotnet core B2C sample:
https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c
